### ISSUE TITLE
Addresses from Amazon with only `AddressLine2` are not recognized

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/woocommerce-gateway-amazon-pay#203]
**Describe the bug**
This issue is related to pull request #169. In some cases, the Address from Amazon pay API does not return AddressLine1 but yes the AddressLine2. Seems to be happening with German addresses. 

Thread of WordPress forum that might explain better. https://wordpress.org/support/topic/addresses-from-amazon-with-only-line-2-are-not-recognized/

**To Reproduce**
1. Install, Activate and do the onboarding the of Amazon Pay plugin (with Euro region)
2. Add product to Cart and go to checkout, using the Express checkout Amazon button. 
3. Check the billing address should be  
![image](https://user-images.githubusercontent.com/43881685/184353945-322e7a77-d336-4781-8027-e80e985ad26e.png)
4. Street address field is present to be filled

**Expected behavior**
Specially for German/Austria addresses the AddressLine2 should be considered as part of the Street address

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by creative-andrew** [comment]
@ChristianAF thanks for creating the issue summary. Waiting for my PR to be approved which will close this issue.

**Comment by creative-andrew** [comment]
@ChristianAF do we have news on this? Is there something wrong with my [PR](https://github.com/woocommerce/woocommerce-gateway-amazon-pay/pull/169)?

**Comment by creative-andrew** [comment]
@dpanta94 @ChristianAF do we have news on this? Is there something wrong with my [PR](https://github.com/woocommerce/woocommerce-gateway-amazon-pay/pull/169)?

**Comment by dpanta94** [comment]
Hey @creative-andrew , yes we do have news. Forgive me for the delay. We have planned a release, which will take place soon.
Your PR won't be included in the upcoming release, but the one after.

- Let me update you about timing as well. Planned release is for Monday 10/10.
- After the release, we ll review your code.
- There will be some conflicts to be resolved. Specifically about the tests being added in your PR. We have removed the file your tests were being added. Feel free to not include any tests, since we are working on them.
- We will pass a build from your branch through Quality assurance
- We will merge your PR into main
- Next release (which isn't planned yet) will include your fix.

Appreciate your help and patience on the matter.

Thank you!

**Comment by creative-andrew** [comment]
@dpanta94 my PR is ready to be merged https://github.com/woocommerce/woocommerce-gateway-amazon-pay/pull/169
